version = 1

test_patterns = ["test/**/*.test.ts"]

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ["nodejs", "mocha"]
  module_system = "es-modules"
  dialect = "typescript"
