name: Node CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install and build
        run: |
          npm ci
          npm run build
      - name: lint
        run: npm run lint
      - name: test
        run: npm run test:coverage
